src/roborally/urls.py
from django.urls import path

from . import views

app_name = 'roborally'
urlpatterns = [
    path('test_scenario', views.TestScenarioView.as_view(), name='test_scenario'),
    path('scenario/<str:scenario_name>', views.ScenarioCanvasPartialView.as_view(), name='scenario_details'),
    path('list', views.ListGamesView.as_view(), name='list'),
    path('new', views.NewGameView.as_view(), name='new'),
    path('play/<int:pk>', views.PlayView.as_view(), name='play'),
    path('history/<int:game_id>/<int:round_number>/<int:phase>', views.HistoryView.as_view(), name='history'),
]

src/roborallyDjango/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView
from django.urls import path, include, re_path

urlpatterns = [
    path('roborally/', include('roborally.urls')),
    path('admin/', admin.site.urls),
    re_path(r'^accounts/login/$', LoginView.as_view(template_name='roborally/login.html'), name="login"),
    re_path(r'^accounts/logout/$', LogoutView.as_view(), name="logout"),
    re_path(r'^accounts/password_reset/$', PasswordResetView.as_view(), name="password_reset"),
]

src/roborally/game/models.py
from abc import ABC, abstractmethod
from typing import Iterable
from roborally.game.direction import Direction
from roborally.game.events import EventType


class MovableModel(ABC):
    x_coordinate: int = -1
    y_coordinate: int = -1
    archive_x_coordinate: int = -1
    archive_y_coordinate: int = -1
    facing_direction: Direction = None

    @property
    def order_number(self) -> int:
        return 0


class BotModel(MovableModel):
    damage: int = 0

    @abstractmethod
    def get_cards_for(self, round: int, phase: int):
        pass

    @abstractmethod
    def log_event(self, phase: int, event_type: EventType, other_model: MovableModel, **kwargs):
        pass


class FlagModel(MovableModel):
    @abstractmethod
    def save(self):
        pass


class GameModel(ABC):

    @abstractmethod
    def get_scenario_data_provider(self):
        pass

    @property
    def bots(self) -> Iterable[BotModel]:
        return []

    @property
    def flags(self) -> Iterable[FlagModel]:
        return []

src/roborally/models/abc.py
from abc import ABC

from django.db import models


class AbstractModelMeta(type(ABC), type(models.Model)):
    pass

src/roborally/models/bot.py
from typing import Self

from django.contrib.auth.models import User
from django.db import models

from roborally.game.card import CardDefinition
from roborally.game.direction import Direction
from roborally.game.events import EventType
from roborally.models.flag import Flag
from roborally.models.game import Game


class Bot(models.Model):
    damage = models.IntegerField(default=0)
    lives = models.IntegerField(default=3)
    x_coordinate = models.IntegerField(default=-1)
    y_coordinate = models.IntegerField(default=-1)
    archive_x_coordinate = models.IntegerField(default=-1)
    archive_y_coordinate = models.IntegerField(default=-1)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)  # TODO: Decide on cascade
    archive_flag = models.OneToOneField(Flag,
                                        on_delete=models.CASCADE,  # TODO: Decide on cascade
                                        null=True,
                                        blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)  # TODO: Decide on cascade
    order_number = models.IntegerField(default=0)
    facing_direction = models.CharField(choices=Direction.get_choices(),
                                        max_length=5
                                        )
    created_by = models.CharField(max_length=250, default='internal')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_by = models.CharField(max_length=250, default='internal')
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.order_number}@{self.game.name}[{self.id}] for {self.user.username}'

    def get_cards_for(self, round, phase) -> list[CardDefinition]:
        return [CardDefinition(card)
                for card
                in self.movementcard_set.filter(round=round, phase=phase, status__in=['FINAL', 'LOCKED'])]

    def log_event(self, phase: int, event_type: EventType, other: Self = None, **kwargs):
        event = self.event_registrar_set.create(round=self.game.current_round,
                                                phase=phase,
                                                event_type=event_type,
                                                other=other,
                                                extra=kwargs)
        event.save()

src/roborally/models/card.py
from django.db import models

from roborally.game.card import CardDefinition
from roborally.models.bot import Bot


class CardStatus(models.TextChoices):
    INITIAL = 'INITIAL'
    FINAL = 'FINAL'
    LOCKED = 'LOCKED'
    FLYWHEEL = 'FLYWHEEL'


class MovementCard(models.Model):
    round = models.IntegerField(default=0)
    phase = models.IntegerField(default=1)
    status = models.CharField(choices=CardStatus.choices,
                              max_length=10,
                              default='INITIAL'
                              )
    bot = models.ForeignKey(Bot, on_delete=models.CASCADE)  # TODO: Decide on cascade
    card_definition = models.CharField(choices=CardDefinition.get_choices(),
                                       max_length=32
                                       )
    optional_text = models.CharField(max_length=250)
    created_by = models.CharField(max_length=250, default='internal')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_by = models.CharField(max_length=250, default='internal')
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.card_definition}@{self.bot.game.name}/{self.phase}/{self.round}[{self.id}]' \
               f' for {self.bot.order_number}'

src/roborally/models/events.py
from django.db import models

from roborally.game.events import EventType
from roborally.models.bot import Bot


class Event(models.Model):
    round = models.IntegerField(default=0)
    phase = models.IntegerField(default=1)
    registrar = models.ForeignKey(Bot,
                                  on_delete=models.CASCADE,
                                  related_name='event_registrar_set')  # TODO: Decide on cascade
    other = models.ForeignKey(Bot,
                              on_delete=models.CASCADE,
                              related_name='event_other_set')  # TODO: Decide on cascade
    type = models.CharField(choices=EventType.get_choices(),
                            max_length=32
                            )
    extra = models.CharField(max_length=2500)
    created_by = models.CharField(max_length=250, default='internal')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.type}@{self.registrar.game.name}@{self.phase}/{self.round}[{self.id}]'

src/roborally/models/flag.py
from django.db import models

from roborally.models.game import Game


class Flag(models.Model):
    x_coordinate = models.IntegerField(default=-1)
    y_coordinate = models.IntegerField(default=-1)
    archive_x_coordinate = models.IntegerField(default=-1)
    archive_y_coordinate = models.IntegerField(default=-1)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)  # TODO: Decide on cascade
    order_number = models.IntegerField(default=0)
    created_by = models.CharField(max_length=250, default='internal')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_by = models.CharField(max_length=250, default='internal')
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.order_number}@{self.game.name}[{self.id}]'

src/roborally/models/game.py
from typing import Iterable

from django.db import models

from roborally.board.data.data_django import DjangoScenarioDataProvider
from roborally.game.models import GameModel, FlagModel, BotModel
from roborally.models.abc import AbstractModelMeta
from roborally.models.scenario import ScenarioName


class GameStatus(models.TextChoices):
    AVAILABLE = 'AVAILABLE'
    CALCULATING = 'CALCULATING'
    FINISHED = 'FINISHED'


class Game(models.Model, GameModel, metaclass=AbstractModelMeta):
    name = models.CharField(max_length=250, unique=True)
    scenario_name = models.CharField(choices=ScenarioName.choices, max_length=250)
    current_round = models.IntegerField(default=0)
    status = models.CharField(choices=GameStatus.choices,
                              max_length=15,
                              default=GameStatus.CALCULATING
                              )
    created_by = models.CharField(max_length=250, default='internal')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_by = models.CharField(max_length=250, default='internal')
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.name}[{self.id}]'

    def get_scenario_data_provider(self):
        return DjangoScenarioDataProvider(self.scenario_name)

    @property
    def bots(self) -> Iterable[BotModel]:
        return self.bot_set

    @property
    def flags(self) -> Iterable[FlagModel]:
        return self.flag_set

src/roborally/models/history.py
from django.db import models

from roborally.models.game import Game


class History(models.Model):
    round = models.IntegerField(default=0)
    phase = models.IntegerField(default=1)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)  # TODO: Decide on cascade
    snapshot_data = models.JSONField
    created_by = models.CharField(max_length=250, default='internal')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.game.name}@{self.phase}/{self.round}[{self.id}]'

src/roborally/models/scenario.py
from django.db import models

from roborally.board.data.loader import ElementTypes
from roborally.game.direction import Direction


class ScenarioName(models.TextChoices):
    MOVING_TARGETS = "MOVING_TARGETS",
    AGAINST_THE_GRAIN = "AGAINST_THE_GRAIN",
    TRICKSY = "TRICKSY",
    ISLAND_KING = "ISLAND_KING",
    ODDEST_SEA = "ODDEST_SEA",
    ROBOT_STEW = "ROBOT_STEW",
    LOST_BEARINGS = "LOST_BEARINGS",
    WHIRLWIND_TOUR = "WHIRLWIND_TOUR",
    VAULT_ASSAULT = "VAULT_ASSAULT",
    PILGRIMAGE = "PILGRIMAGE",
    DEATH_TRAP = "DEATH_TRAP",
    AROUND_THE_WORLD = "AROUND_THE_WORLD",
    BLOODBATH_CHESS = "BLOODBATH_CHESS",
    TWISTER = "TWISTER",
    CHOP_SHOP_CHALLENGE = "CHOP_SHOP_CHALLENGE",
    ISLAND_HOP = "ISLAND_HOP",
    DIZZY_DASH = "DIZZY_DASH",
    CHECKMATE = "CHECKMATE",
    RISKY_EXCHANGE = "RISKY_EXCHANGE",
    SET_TO_KILL = "SET_TO_KILL",
    FACTORY_REJECTS = "FACTORY_REJECTS",
    OPTION_WORLD = "OPTION_WORLD",
    TIGHT_COLLAR = "TIGHT_COLLAR",
    BALL_LIGHTNING = "BALL_LIGHTNING",
    DAY_OF_THE_SUPERBOT = "DAY_OF_THE_SUPERBOT",
    INTERFERENCE = "INTERFERENCE",
    FLAG_FRY = "FLAG_FRY",
    FRENETIC_FACTORY = "FRENETIC_FACTORY"
    MARATHON_MADNESS = "MARATHON_MADNESS",
    TANDEM_CARNAGE = "TANDEM_CARNAGE",
    ALL_FOR_ONE = "ALL_FOR_ONE"
    CAPTURE_THE_FLAG = "CAPTURE_THE_FLAG",
    TOGGLE_BOGGLE = "TOGGLE_BOGGLE",
    WAR_ZONE = "WAR_ZONE"


class BoardName(models.TextChoices):
    STARTING_BOARD_1 = "STARTING_BOARD_1",
    STARTING_BOARD_2 = "STARTING_BOARD_2",
    MAELSTROM = "MAELSTROM",
    SPIN_ZONE = "SPIN_ZONE",
    VAULT = "VAULT",
    CROSS = "CROSS",
    CHESS = "CHESS",
    CHOP_SHOP = "CHOP_SHOP",
    ISLAND = "ISLAND",
    EXCHANGE = "EXCHANGE"


class ScenarioBoard(models.Model):
    name = models.CharField(choices=ScenarioName.choices,
                            max_length=50)
    turns = models.IntegerField(default=0)
    offset_x = models.IntegerField(default=0)
    offset_y = models.IntegerField(default=0)
    board_name = models.CharField(choices=BoardName.choices,
                                  max_length=20)


class ScenarioFlag(models.Model):
    name = models.CharField(choices=ScenarioName.choices,
                            max_length=50)
    x_coordinate = models.IntegerField(default=-1)
    y_coordinate = models.IntegerField(default=-1)
    order_number = models.IntegerField(default=0)


class BoardElement(models.Model):
    name = models.CharField(choices=BoardName.choices,
                            max_length=20)
    element_type = models.CharField(choices=ElementTypes.get_choices(),
                                    max_length=50)
    x_coordinate = models.IntegerField(default=-1)
    y_coordinate = models.IntegerField(default=-1)
    direction = models.CharField(choices=Direction.get_choices(),
                                 max_length=5,
                                 null=True,
                                 blank=True)

    def to_dict(self):
        return {'name': self.name,
                'element_type': ElementTypes(self.element_type) if self.element_type else None,
                'x_coordinate': self.x_coordinate,
                'y_coordinate': self.y_coordinate,
                'direction': Direction(self.direction) if self.direction else None
                }

src/roborally/forms.py
from django.contrib.auth.models import User
from django.forms import ModelForm, ModelMultipleChoiceField, Select

from roborally.models import Game


class ScenarioNameWithPreview(Select):
    template_name = 'roborally/scenario_name_field.html'


class GameForm(ModelForm):
    class Meta:
        model = Game
        fields = ['name', 'scenario_name']
        widgets = {'scenario_name': ScenarioNameWithPreview()}
    users = ModelMultipleChoiceField(queryset=User.objects.all())

src/roborally/views.py
from os import path

from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import generic

from roborally.board.data.data_django import DjangoScenarioDataProvider
from roborally.board.data.data_json import JSONScenarioDataProvider
from roborally.models import Game, History, Bot
from roborally.forms import GameForm
from roborally.board.scenario import Scenario


# Test canvas
class TestScenarioView(generic.TemplateView):
    template_name = 'roborally/test_scenario.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        with open(path.join(path.split(__file__)[0],  "../../tests/roborally_tests/board/test_scenario.json"), 'r') as f:
            scenario_data_provider = JSONScenarioDataProvider(f.read())
        board_data = Scenario(scenario_data_provider, True).to_data()
        context['board'] = board_data
        return context


class ScenarioCanvasPartialView(generic.TemplateView):
    template_name = 'roborally/canvas.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        scenario_data_provider = DjangoScenarioDataProvider(kwargs["scenario_name"].upper())
        board_data = Scenario(scenario_data_provider, True).to_data()
        context['board'] = board_data
        return context


# list games
@method_decorator(login_required, name='dispatch')
class ListGamesView(generic.ListView):
    template_name = 'roborally/list.html'
    context_object_name = 'game_list'

    def get_queryset(self):
        return Game.objects.filter(bot__user=self.request.user)


@method_decorator(login_required, name='dispatch')
class NewGameView(generic.CreateView):
    template_name = 'roborally/new.html'
    form_class = GameForm
    context_object_name = 'game_form'

    def form_valid(self, form):
        form.instance.created_by = self.request.user.id
        response = super().form_valid(form)
        # add bot for the current user
        bot = Bot(game=self.object,
                  user=self.request.user,
                  created_by=self.request.user.id,
                  updated_by=self.request.user.id)
        bot.save()
        # add bots for the chosen users
        for player in form.cleaned_data['users']:
            bot = Bot(game=self.object,
                      user=player,
                      created_by=self.request.user.id,
                      updated_by=self.request.user.id)
            bot.save()
        return response

    def get_success_url(self):
        return reverse('roborally:play', kwargs={'pk': self.object.pk})


# see current game state
@method_decorator(login_required, name='dispatch')
class PlayView(generic.DetailView):
    model = Game
    template_name = 'roborally/play.html'


# popup for history?
@method_decorator(login_required, name='dispatch')
class HistoryView(generic.DetailView):
    context_object_name = 'history'
    model = History
    template_name = 'roborally/history.html'

    def get_queryset(self):
        return History.objects.get(game_id=self.kwargs['game_id'],
                                   round=self.kwargs['round_number'],
                                   phase=self.kwargs['phase'])

src/roborally/templates/roborally/canvas.html
{{ board|json_script:"board_data" }}
<canvas id="board">

</canvas>

src/roborally/templates/roborally/history.html
{% extends "roborally/index.html" %}

{% block content %}
{{ history.game.name }} @ {{ history.phase }} / {{ history.round }}
{% endblock content %}

src/roborally/templates/roborally/index.html
<!DOCTYPE html>
<html lang="en">
<head>
{% load static %}

    <meta charset="UTF-8">
    <title>{% block title %}Play roborally{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'roborally/css/roborally.css' %}">
    <script src="{% static 'roborally/js/fabric.min.js' %}" defer></script>
    <script src="{% static 'roborally/js/bootstrap.bundle.min.js' %}" defer></script>
    <script src="{% static 'roborally/js/roborally.js' %}" defer></script>
</head>
<body>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

src/roborally/templates/roborally/list.html
{% extends "roborally/index.html" %}

{% block content %}
    {% if game_list %}
        <ul>
        {% for game in game_list %}
            <li><a href="{% url 'roborally:play' game.id %}">{{ game.name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No games are available.</p>
    {% endif %}
{% endblock content %}

src/roborally/templates/roborally/login.html
{% extends "roborally/index.html" %}

{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login">
<input type="hidden" name="next" value="{{ next }}">
</form>

{# Assumes you set up the password_reset view in your URLconf #}
<p><a href="{% url 'password_reset' %}">Lost password?</a></p>

{% endblock %}

src/roborally/templates/roborally/new.html
{% extends "roborally/index.html" %}

{% block content %}
    <script>
        function load_scenario_preview(scenario_name) {
            const scenario_preview = document.getElementById('scenario_preview')
            fetch(new Request('/roborally/scenario/' + scenario_name))
                .then((response) => response.text())
                .then((text) => {
                    scenario_preview.innerHTML=text
                    const roborally = new Roborally(JSON.parse(document.getElementById('board_data').textContent), 'board');
                    roborally.draw_canvas();
                })
        }
    </script>
    <div class="d-flex">
        <div>
            <form action="{% url 'roborally:new' %}" method="post">
                {% csrf_token %}
                <table>
                {{ form.as_table }}
                </table>
                <input type="submit" value="Create">
            </form>
        </div>
        <div id="scenario_preview">

        </div>
    </div>
{% endblock content %}

src/roborally/templates/roborally/play.html
{% extends "roborally/index.html" %}

{% block content %}
{{ game.name }}
{% endblock content %}

src/roborally/templates/roborally/scenario_name_field.html
<select name="{{ widget.name }}"{% include "django/forms/widgets/attrs.html" %}>{% for group_name, group_choices, group_index in widget.optgroups %}{% if group_name %}
  <optgroup label="{{ group_name }}">{% endif %}{% for option in group_choices %}
  {% include option.template_name with widget=option %}{% endfor %}{% if group_name %}
  </optgroup>{% endif %}{% endfor %}
</select>
<script>
    document.getElementsByName('{{ widget.name }}').forEach((scenario_name_select) => {
        scenario_name_select.addEventListener('change', (event) => {
            if (event.target.value) {
                load_scenario_preview(event.target.value)
            }
        })
    })
</script>

src/roborally/templates/roborally/test_scenario.html
{% extends "roborally/index.html" %}

{% block content %}
    <div id="scenario_preview">
    {%  include "roborally/canvas.html" %}
    </div>
    <script>
        document.addEventListener('DOMContentLoaded', () => {
            const roborally = new Roborally(JSON.parse(document.getElementById('board_data').textContent), 'board');
            roborally.draw_canvas();
        });
    </script>
{% endblock content %}